# Generated by Django 2.0.1 on 2018-01-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuqueue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='queue_no',
        ),
        migrations.AddField(
            model_name='detail',
            name='lineno',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
