# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-14 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuqueue', '0003_detail_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name=b'check',
        ),
    ]
