# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuqueue', '0004_remove_detail_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detail',
            new_name='details',
        ),
    ]
