# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-25 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuqueue', '0005_auto_20180326_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
